language: rust
sudo: false

matrix:
  include:
    - env: FEATURES=""
           NDF="--no-default-features"
    - env: FEATURES="serde"
           NDF=""
    - env: FEATURES="std"
           NDF=""
    - env: FEATURES="v1"
           NDF=""
    - env: FEATURES="v3"
           NDF=""
    - env: FEATURES="v4"
           NDF=""
    - env: FEATURES="v5"
           NDF=""
    - env: FEATURES="serde v1 v3 v4 v5 std"
           NDF=""
    - rust: beta
    - rust: nightly

    - rust: nightly
      script: cargo bench --all-features

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps --all-features
      after_success:
        - travis-cargo --only nightly doc-upload

script:
  - cargo test --features "$FEATURES" $NDF

env:
  global:
    secure: "HzcZYuf80pByt4J3OM+sfXg5dGPQjFTPfLYR907wfi8FD6mJu5yYbgPF4agz9sdnnNrtnmlghZ5WFljrl49oNC6RhcSc6YVmiRKs4DabMKKr3v9zZy1i2KuQ323cGpwUIVpq7+u8/vQAYPwRUPzZrVw57y5KKqEHbn2T85yFdqo="

notifications:
  email:
    on_success: never

branches:
    except:
    - /.*(.tmp)$/

