language: rust
sudo: false

matrix:
  include:
    - env: FEATURES=""
    - env: FEATURES="rustc-serialize"
    - env: FEATURES="serde"
    - env: FEATURES="use_std"
    - env: FEATURES="v1"
    - env: FEATURES="v3"
    - env: FEATURES="v4"
    - env: FEATURES="v5"
    - env: FEATURES="rustc-serialize serde v1 v3 v4 v5 use_std"
    - rust: beta
    - rust: nightly

    - rust: nightly
      script: cargo bench --all-features

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps --all-features
      after_success:
        - travis-cargo --only nightly doc-upload

script:
  - cargo test --features "$FEATURES"

env:
  global:
    secure: "HzcZYuf80pByt4J3OM+sfXg5dGPQjFTPfLYR907wfi8FD6mJu5yYbgPF4agz9sdnnNrtnmlghZ5WFljrl49oNC6RhcSc6YVmiRKs4DabMKKr3v9zZy1i2KuQ323cGpwUIVpq7+u8/vQAYPwRUPzZrVw57y5KKqEHbn2T85yFdqo="

notifications:
  email:
    on_success: never
