branches:
  except:
  - /.*(.tmp)$/

language: rust

matrix:
  include:
  - rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --write-mode=check
    - cargo test --features "serde std v1 v3 v4 v5"
    - cargo bench --features "serde std v1 v3 v4 v5"

notifications:
  email:
    on_success: never

os:
- linux
- osx

rust:
- 1.18.0
- stable
- beta
- nightly

script:
- cargo build --no-default-features
- cargo build
- cargo build --features "serde"
- cargo build --features "v1"
- cargo build --features "v3"
- cargo build --features "v4"
- cargo build --features "v5"
- cargo build --features "serde std v1 v3 v4 v5"

sudo: false
