language: rust
sudo: false

matrix:
  include:
    - env: FEATURES=""
           NDF="--no-default-features"
    - env: FEATURES="serde"
    - env: FEATURES="std"
    - env: FEATURES="v1"
    - env: FEATURES="v3"
    - env: FEATURES="v4"
    - env: FEATURES="v5"
    - env: FEATURES="serde v1 v3 v4 v5 std"
    - rust: 1.18.0
    - rust: beta
    - rust: nightly

    - rust: nightly
      script: cargo bench --all-features
    
    - rust: nightly
      cache: cargo
      before_script:
        - rustup component add rustfmt-preview
#        - ( cargo install clippy || true )
      script:
        - cargo fmt --all -- --write-mode=diff
        - cargo test
#        - cargo clippy

script:
  - cargo test --features "$FEATURES" $NDF

notifications:
  email:
    on_success: never

branches:
    except:
    - /.*(.tmp)$/

