[package]
authors = [
    "Ashley Mannix<ashleymannix@live.com.au>",
    "Christopher Armstrong",
    "Dylan DPC<dylan.dpc@gmail.com>",
    "Hunar Roop Kahlon<hunar.roop@gmail.com>"
]
description = "A library to generate and parse UUIDs."
documentation = "https://docs.rs/uuid"
exclude = [
    ".github/**",
    ".travis.yml",
    "appveyor.yml",
    "bors.toml"
]
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/uuid-rs/uuid"
name = "uuid"
readme = "README.md"
repository = "https://github.com/uuid-rs/uuid"
version = "0.6.3"

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
features = ["serde", "u128", "v1", "v3", "v4", "v5"]

[dependencies]
serde = { version = "1.0.56", optional = true, default-features = false }
rand = { version = "0.4", optional = true }
sha1 = { version = "0.6", optional = true }
md5 = { version = "0.3", optional = true }
slog = { version = "2", optional = true }
cfg-if = "0.1.2"

[dependencies.byteorder]
default-features = false
features = ["i128"]
optional = true
version = "1"

[dev-dependencies]
serde_test = "1.0.56"

[features]
default = ["std"]
nightly = []
std = []
use_std = ["std"] # Compatibility shim for 0.5 and earlier
v1 = []
v3 = ["md5", "rand"]
v4 = ["rand"]
v5 = ["sha1", "rand"]

# since rust 1.26.0
u128 = ["byteorder"]

# only rust nightly
const-fn = ["nightly"]
