[package]

name = "uuid"
version = "0.1.18"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "https://doc.rust-lang.org/uuid"
description = """
A library to generate and parse UUIDs.
"""

[dependencies]
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "^0.7.0", optional = true }
rand = "0.3"
