[package]

name = "uuid"
version = "0.1.3"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "http://doc.rust-lang.org/uuid"
description = """
A library to generate and parse UUIDs.
"""

[dependencies]
rustc-serialize = "0.1"
