[package]

name = "uuid"
version = "0.0.2"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
description = """
A library to generate and parse UUIDs.
"""
