name: Clippy

on: [push, pull_request]

jobs:
  mac-clippy:
    name: macOS
    runs-on: macOS-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Toolchain
       uses: actions-rs/toolchain@v1
       with:
         components: clippy
         override: true
         profile: minimal
         toolchain: 1.32.0
     - name: Run `cargo clippy`
       uses: actions-rs/cargo@v1
       with:
         command: clippy
         args: --features "serde slog std v1 v3 v4 v5" -- -D warnings
  linux-clippy:
   name: Linux
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Toolchain
       uses: actions-rs/toolchain@v1
       with:
         components: clippy
         override: true
         profile: minimal
         toolchain: 1.32.0
     - name: Run `cargo clippy`
       uses: actions-rs/cargo@v1
       with:
         command: clippy
         args: --features "serde slog std v1 v3 v4 v5" -- -D warnings
  windows-clippy:
   name: Windows
   runs-on: windows-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Toolchain
       uses: actions-rs/toolchain@v1
       with:
         components: clippy
         override: true
         profile: minimal
         toolchain: 1.32.0
     - name: Run `cargo clippy`
       uses: actions-rs/clippy-check@v1
       with:
         args: --all-features -- -D warnings
         token: ${{ secrets.GITHUB_TOKEN }}
